#!/bin/sh

#
# Hardware type, "FlashAir" or "Transcend"

HWTYPE="FlashAir"
#HWTYPE="Transcend"

#
# Network interface for wifi connection
#
WLANIF="wlan0"

#
# Connection name and SSID of the FlashAir card
#

SSID="FA-XP1"

#
# Local directory above the copy of the camera's DCIM directory
#
BASEDIR="/home/user/Desktop/Photos/Camera1"

#
# FlashAir URL above the DCIM directory
#

BASEURL="http://192.168.0.1"
#BASEURL="http://192.168.11.254"

check="true"
for ex in \
 echo echo sleep date grep sed cut tail nmcli wget
  do
    loc=$(which "${ex}")
    if [ "${loc}" = "" ]
      then
        echo "${ex} is missing"
        check="false"
    fi
done

if [ "${check}" = "false" ]
  then
    echo "Some utilities are missing"
    exit 1
fi

#
# Utilities
#
ECHO=$(which echo)

#
# Sanitize file name for interaction with FlashAir
#
sstring()
{
sed -e 's/[^a-zA-Z0-9./_-]/_/g' \
 -e 's/^\.\.\//_\.\.\//' \
 -e 's/\/\.\.\//\/_\.\._\//g'
}
#
# Sanitize numbers for interaction with FlashAir
#

nstring()
{
sed 's/[^0-9]//g'
}

#
# Display a single step of a spinner
# on a VT100-compatible terminals
#
spinner_char=""
spinner()
{
if [ "${spinner_char}" = "-" ] ; then spinner_char="\\" ; else
if [ "${spinner_char}" = "\\" ] ; then spinner_char="|" ; else
if [ "${spinner_char}" = "|" ] ; then spinner_char="/" ; else
 spinner_char="-" ;
fi;fi;fi
${ECHO} -ne "\x1b[1D${spinner_char}"
}

#
# Get directory from FlashAir card
#
fa_getdirectory()
{
dir="${1}"
wget -q -O- "${BASEURL}${dir}" | \
  grep -E '(^wlansd\[[0-9]+\]=)|(^wlansd\.push\({)' | \
  while read line
    do
      if echo "${line}" | grep -q -E '^wlansd\[[0-9]+\]='
        then
          line=$(echo "${line}" | cut -d\" -f2)
          filename=$(echo "${line}" | cut -d, -f2 | sstring)
          upfilename=$(echo "${line}" | cut -d, -f1 | sstring)
          filesize=$(echo "${line}" | cut -d, -f3 | nstring)
          if [ "${filesize}" = "0" ]
            then
              echo "DIR"
          else
              echo "FILE"
          fi
          echo "${filesize}"
          echo "${upfilename}"
          echo "${filename}"
      else
          echo "${line}" | cut -d\{ -f2- | sed 's/\});$//' | \
            tr ',' '\n' | sed -e 's/^ \+//' -e 's/ \+$//' | \
            (
              filetype=""
              filesize=""
              upfilename=""
              filename=""
              finished=""
              while read line
                do
                  key=$(echo "${line}" | cut -d':' -f1)
                  value=$(echo "${line}" | cut -d':' -f2-)
                  key=$(echo "${key}" | \
                       sed -e 's/ *\"//' -e 's/\" *$//' | sstring)
                  value=$(echo "${value}" | \
                       sed -e 's/ *\"//' -e 's/\" *$//' | sstring)
                  case "${key}" in
                    "r_uri")
                      upfilename="${value}"
                      ;;
                    "fname")
                      filename="${value}"
                      ;;
                    "fsize")
                      filesize=$(echo "${value}" | nstring)
                      ;;
                    "*")
                      ;;
                  esac
                  if [ "${finished}" != "y" \
                       -a "${filesize}" != "" \
                       -a "${filename}" != "" \
                       -a "${upfilename}" != "" ]
                    then
                      finished="y"
                      if [ "${filesize}" = "0" ]
                        then
                          echo "DIR"
                      else
                          echo "FILE"
                      fi
                      echo "${filesize}"
                      echo "${upfilename}"
                      echo "${filename}"
                  fi
                done
            )
      fi
    done
}

#
# Get directory from Transcend card
#
ts_getdirectory()
{
dir="${1}"
count=""
filename=""
filetype=""
wget -q -O- "${BASEURL}/cgi-bin/tslist?PATH=${dir}" | \
  grep "FileName0=" | \
  tr '&' '\n' | \
  grep -E "File.*[0-9]*=" | \
  grep -v "FileCount=" | \
  while read line
    do
      newcount=$(echo "${line}" | sed -e "s/^[A-Za-z]*//" -e "s/=.*$//")
      if [ "${count}" != "" -a  "${newcount}" != "${count}" ]
        then
            filename=""
            filetype=""
      fi
      key=$(echo "${line}" | sed "s/[0-9=].*$//" | sstring)
      value=$(echo "${line}" | sed "s/^.*=//" | sstring)
      count="${newcount}"
      if [ "${key}" = "FileName" ]
        then
          filename="${value}"
      else
        if [ "${key}" = "FileType" ]
          then
            filetype="${value}"
        fi
      fi
      if [ "${filename}" != "" -a "${filetype}" != "" ]
        then
          if [ "${filetype}" = "File" ]
            then
              filesize=$(wget -q -O- "${BASEURL}/cgi-bin/tscmd?\
CMD=GET_FILE_INFO&FILE=${dir}/${filename}" \
               |  grep -i "File size:" | \
               sed -e "s/^.*:[^0-9]*//" -e "s/[^0-9]*$//" | nstring)
              echo "FILE"
              echo "${filesize}"
              echo "${filename}"
          else
            if [ "${filetype}" = "Directory" ]
              then
                echo "DIR"
                echo "0"
                echo "${filename}"
            fi
          fi
          filename=""
          filetype=""
      fi
    done
}


#
# Cleanup procedure for exit and signal handler
#
restore_wlan()
{
if [ "${orig_conn}" = "--" ]
  then
    echo "Disconnecting from ${SSID}"
    nmcli connection down "${SSID}" >/dev/null 2>&1
else
  if [ "${orig_conn}" != "${SSID}" ]
    then
      echo "Restoring connection ${orig_conn}"
      nmcli connection up "${orig_conn}" ifname "${WLANIF}" >/dev/null 2>&1
  fi
fi
}

#
# Check if $SSID is the current connection, and
# connect to it if this is not the case.
#
# This procedure will wait indefinitely if the
# connection is not available.
#
check_wlan()
{
curr_conn=$(nmcli device show "${WLANIF}" 2>/dev/null | \
  grep -F 'GENERAL.CONNECTION:' | \
  sed -e 's/^.*: *//')
while [ "${curr_conn}" != "${SSID}" ]
  do
    if [ "${curr_conn}" != "--" ]
      then
        nmcli connection down "${curr_conn}" >/dev/null 2>&1
    fi
    ${ECHO} -n "Scanning..."
    nmcli device wifi rescan ifname "${WLANIF}" 2>/dev/null
    ${ECHO} -n " Looking for ${SSID}... "
    lasttime=$(($(date +%s)/20))
    found=""
    while [ "${found}" = "" ]
      do
        currtime=$(($(date +%s)/20))
        if [ "${currtime}" != "${lasttime}" ]
          then
            ${ECHO} -ne "\x0d\x1b[JScanning..."
            nmcli device wifi rescan ifname "${WLANIF}" 2>/dev/null
            sleep 10
            ${ECHO} -n " Looking for ${SSID}... "
            lasttime=$(($(date +%s)/20))
        fi
        sleep .5
        found=$(nmcli device wifi list ifname "${WLANIF}" 2>/dev/null | \
          sed -e 's/^\** *//' | cut -d' ' -f1 | tail -n +2 | \
          grep -F "${SSID}")
        spinner
      done
    ${ECHO} -ne "\x0d\x1b[JConnecting to ${SSID}..."
    nmcli connection up "${SSID}" ifname "${WLANIF}" >/dev/null 2>&1
    curr_conn=$(nmcli device show "${WLANIF}" 2>/dev/null | \
      grep -F 'GENERAL.CONNECTION:' | \
      sed -e 's/^.*: *//')
    if [ "${curr_conn}" = "${SSID}" ]
      then
        ${ECHO} -e "\x0d\x1b[JConnected to ${SSID}"
    else
      echo " Failure"
    fi
  done
}

#
# Main body of the script
#
orig_conn=$(nmcli device show "${WLANIF}" 2>/dev/null | \
  grep -F 'GENERAL.CONNECTION:' | \
  sed -e 's/^.*: *//')

trap "echo "" ; restore_wlan; exit 0" 1 2 15

if [ "${orig_conn}" != "--" ]
  then
    echo "Originally connected to ${orig_conn}"
fi

check_wlan

case "${HWTYPE}" in

    "FlashAir")
fa_getdirectory "/DCIM/" | \
while read filetype
  do
    read filesize
    read dir
    read upfilename
    if [ "${dir}" = "/DCIM" -a "${filetype}" = "DIR" -a "${filesize}" = "0" ]
      then
        check_wlan
        fa_getdirectory "/DCIM/${upfilename}" | \
            while read filetype
  do
              read filesize
              read dir
              read filename
              if [ "${dir}" = "/DCIM/${upfilename}" -a "${filetype}" = "FILE" ]
      then
        local_filesize=$(stat -c "%s" \
                              "${BASEDIR}/${dir}/${filename}" 2>/dev/null )
        if [ "${local_filesize}" != "${filesize}" ]
          then
            [ -d "${BASEDIR}/${dir}" ] || \
              mkdir -p "${BASEDIR}/${dir}"
            check_wlan
            wget -O "${BASEDIR}/${dir}/${filename}" \
                 "${BASEURL}/${dir}/${filename}"
        fi
    fi
  done
    fi
  done
;;

    "Transcend")
ts_getdirectory "/www/sd/DCIM" | \
  while read filetype
    do
      read filesize
      read filename
      if [ "${filetype}" = "DIR" ]
        then
          dir="${filename}"
          check_wlan
          ts_getdirectory "/www/sd/DCIM/${dir}" | \
            while read filetype
              do
                read filesize
                read filename
                if [ "${filetype}" = "FILE" ]
                  then
                    local_filesize=$(stat -c "%s" \
                                        "${BASEDIR}/DCIM/${dir}/${filename}" \
                                        2>/dev/null )
                    if [ "${local_filesize}" != "${filesize}" ]
                      then
                        [ -d "${BASEDIR}/DCIM/${dir}" ] || \
                          mkdir -p "${BASEDIR}/DCIM/${dir}"
                        check_wlan
                        wget -O "${BASEDIR}/DCIM/${dir}/${filename}" \
                             "${BASEURL}/sd/DCIM/${dir}/${filename}"
                    fi
                fi
              done
      fi
    done
;;
    *)
echo "Unknown HWTYPE ${HWTYPE}" >&2
;;
esac
restore_wlan
